name = "twitter-discord"

compatibility_date = "2022-05-11"

main = "build/twitter-discord/index.js"

kv_namespaces = [
    { binding = "DATA", id = "953d3bc5fd1f4f0cbdbc97a996c7ca86" }
]

[build]
command = "npm run build"

[triggers]
crons = ["*/5 * * * *"]